package mcl.compiler.parser.nodes.blocks;

import mcl.compiler.MCLCompiler;
import mcl.compiler.analyzer.RuntimeType;
import mcl.compiler.exceptions.MCLError;
import mcl.compiler.parser.AbstractNode;
import mcl.compiler.source.MCLSourceCollection;
import mcl.compiler.transpiler.MCLTranspiler;

import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import java.util.function.BiConsumer;

public class ProgramRootNode extends AbstractNode
{
    public final List<AbstractNode> namespaces;

    public ProgramRootNode(List<AbstractNode> namespaces)
    {
        super(0, namespaces.size() > 0 ? namespaces.get(namespaces.size() - 1).endPosition() : 1);

        this.namespaces = Collections.unmodifiableList(namespaces);
    }

    @Override
    public void walk(BiConsumer<AbstractNode, AbstractNode> parentChildConsumer)
    {
        for (AbstractNode namespace : namespaces)
        {
            parentChildConsumer.accept(this, namespace);
            namespace.walk(parentChildConsumer);
        }
    }

    @Override
    public MCLError createSymbols(MCLCompiler compiler, MCLSourceCollection source)
    {
        for (AbstractNode namespace : namespaces)
        {
            MCLError error = namespace.createSymbols(compiler, source);
            if (error != null) return error;
        }
        return null;
    }
    @Override
    public MCLError symbolAnalysis(MCLCompiler compiler, MCLSourceCollection source)
    {
        for (AbstractNode namespace : namespaces)
        {
            MCLError error = namespace.symbolAnalysis(compiler, source);
            if (error != null) return error;
        }
        return null;
    }

    @Override
    public MCLError transpile(MCLTranspiler transpiler, Path target)
    {
        MCLError error;

        // Write pack.mcmeta
        Path packMeta = target.resolve("pack.mcmeta");
        error = transpiler.appendToFile(packMeta, file ->
        {
            file.println('{');
            file.println("    \"pack\": {");
            file.println("        \"pack_format\": 10,");
            file.println("        \"description\": \"Datapack generated by MCL. Project: \"" + transpiler.getConfig().projectName);
            file.println("    }");
            file.println('}');
        });
        if (error != null) return error;

        // Data folder
        Path dataFolder = target.resolve("data");
        dataFolder.toFile().mkdirs();

        // Transpile namespaces
        for (AbstractNode namespace : namespaces)
        {
            error = namespace.transpile(transpiler, dataFolder);
            if (error != null) return error;
        }

        return null;
    }

    @Override
    public RuntimeType getRuntimeType(MCLCompiler compiler)
    {
        return RuntimeType.UNDEFINED;
    }

    @Override
    public void debugPrint(int depth)
    {
        System.out.print("  ".repeat(depth));
        System.out.println("PROGRAM");
        for (AbstractNode namespace : namespaces) namespace.debugPrint(depth + 1);
    }
}
