package mcl.compiler.parser.nodes.blocks;

import mcl.compiler.MCLCompiler;
import mcl.compiler.analyzer.RuntimeType;
import mcl.compiler.exceptions.MCLError;
import mcl.compiler.parser.AbstractNode;
import mcl.compiler.source.MCLSourceCollection;
import mcl.compiler.transpiler.MCLTranspiler;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;

public class ProgramRootNode extends AbstractNode
{
    public final List<AbstractNode> namespaces;
    private final Map<String, NamespaceDefinitionNode> namespaceMap;
    private final Map<Path, ProgramRootNode> headers;

    public ProgramRootNode(List<AbstractNode> namespaces)
    {
        super(0, namespaces.size() > 0 ? namespaces.get(namespaces.size() - 1).endPosition() : 1);

        this.namespaces = Collections.unmodifiableList(namespaces);
        this.headers = new HashMap<>();

        Map<String, NamespaceDefinitionNode> map = new HashMap<>();
        for (AbstractNode namespace : namespaces)
        {
            if (namespace instanceof NamespaceDefinitionNode namespaceNode)
            {
                map.put((String)namespaceNode.identifier.value(), namespaceNode);
            }
        }
        this.namespaceMap = Collections.unmodifiableMap(map);
    }

    public void addHeaderSyntaxTree(Path header, ProgramRootNode headerSyntaxTree)
    {
        headers.put(header, headerSyntaxTree);
    }
    public NamespaceDefinitionNode getNamespaceNode(String name)
    {
        NamespaceDefinitionNode namespace = namespaceMap.get(name);
        if (namespace == null)
        {
            for (ProgramRootNode header : headers.values())
            {
                namespace = header.namespaceMap.get(name);
                if (namespace != null) return namespace;
            }
        }
        return namespace;
    }

    @Override
    public void walk(BiConsumer<AbstractNode, AbstractNode> parentChildConsumer)
    {
        for (AbstractNode namespace : namespaces)
        {
            parentChildConsumer.accept(this, namespace);
            namespace.walk(parentChildConsumer);
        }
        for (ProgramRootNode header : headers.values()) header.walk(parentChildConsumer);
    }

    @Override
    public MCLError createSymbols(MCLCompiler compiler, MCLSourceCollection source)
    {
        for (AbstractNode namespace : namespaces)
        {
            MCLError error = namespace.createSymbols(compiler, source);
            if (error != null) return error;
        }
        for (Map.Entry<Path, ProgramRootNode> entry : headers.entrySet())
        {
            source.openHeader = entry.getKey();
            MCLError error = entry.getValue().createSymbols(compiler, source);
            if (error != null) return error;
            source.openHeader = null;
        }
        return null;
    }
    @Override
    public MCLError symbolAnalysis(MCLCompiler compiler, MCLSourceCollection source)
    {
        for (AbstractNode namespace : namespaces)
        {
            MCLError error = namespace.symbolAnalysis(compiler, source);
            if (error != null) return error;
        }
        for (Map.Entry<Path, ProgramRootNode> entry : headers.entrySet())
        {
            source.openHeader = entry.getKey();
            MCLError error = entry.getValue().symbolAnalysis(compiler, source);
            if (error != null) return error;
            source.openHeader = null;
        }
        return null;
    }

    @Override
    public void setTranspileTarget(MCLTranspiler transpiler, Path target) throws IOException
    {
        this.transpileTarget = target;
        Path dataFolder = target.resolve("data");
        transpiler.createDirectory(dataFolder);

        // Set Namespace Targets
        for (AbstractNode namespace : namespaces) namespace.setTranspileTarget(transpiler, dataFolder);

        // Set Header Targets
        for (Map.Entry<Path, ProgramRootNode> entry : headers.entrySet())
        {
            transpiler.enabled = false;
            transpiler.getSource().openHeader = entry.getKey();
            entry.getValue().setTranspileTarget(transpiler, target);
            transpiler.getSource().openHeader = null;
            transpiler.enabled = true;
        }
    }
    @Override
    public MCLError transpile(MCLTranspiler transpiler) throws IOException
    {
        MCLError error;

        // Write pack.mcmeta
        Path packMeta = transpileTarget.resolve("pack.mcmeta");
        error = transpiler.appendToFile(packMeta, file ->
        {
            file.println('{');
            file.println("    \"pack\": {");
            file.println("        \"pack_format\": 10,");
            file.println("        \"description\": \"Datapack generated by MCL. Project: " + transpiler.getConfig().projectName + "\"");
            file.println("    }");
            file.println('}');
        });
        if (error != null) return error;

        // Transpile namespaces
        for (AbstractNode namespace : namespaces)
        {
            error = namespace.transpile(transpiler);
            if (error != null) return error;
        }

        // Transpile headers
        for (Map.Entry<Path, ProgramRootNode> entry : headers.entrySet())
        {
            transpiler.enabled = false;
            transpiler.getSource().openHeader = entry.getKey();

            error = entry.getValue().transpile(transpiler);
            if (error != null) return error;

            transpiler.getSource().openHeader = null;
            transpiler.enabled = true;
        }

        return null;
    }

    @Override
    public RuntimeType getRuntimeType(MCLCompiler compiler)
    {
        return RuntimeType.UNDEFINED;
    }

    @Override
    public void debugPrint(int depth)
    {
        System.out.print("  ".repeat(depth));
        System.out.println("PROGRAM");
        for (AbstractNode namespace : namespaces) namespace.debugPrint(depth + 1);

        System.out.print("  ".repeat(depth));
        System.out.println("HEADERS");
        for (ProgramRootNode header : headers.values()) header.debugPrint(depth + 1);
    }
}
